-- MySQL Script generated by MySQL Workbench
-- jue 24 oct 2019 10:14:44 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `idBook` INT NOT NULL,
  `Title` MEDIUMTEXT NOT NULL,
  `Author` MEDIUMTEXT NOT NULL,
  `Editorial` MEDIUMTEXT NOT NULL,
  `Price` DECIMAL(10,0) NOT NULL,
  `URL` VARCHAR(45) NOT NULL,
  `Stock` DECIMAL(10,0) NOT NULL,
  `NumBook` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `Name` MEDIUMTEXT NOT NULL,
  `LastName` MEDIUMTEXT NOT NULL,
  `DNI` MEDIUMTEXT NOT NULL,
  `Adress` MEDIUMTEXT NOT NULL,
  `IdBook` INT NOT NULL,
  `Password` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Book_idBook` INT NOT NULL,
  INDEX `fk_Client_Book_idx` (`Book_idBook` ASC),
  CONSTRAINT `fk_Client_Book`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `mydb`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
