-- MySQL Script generated by MySQL Workbench
-- jue 24 oct 2019 11:11:15 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Empresa` MEDIUMTEXT NOT NULL,
  `Calle` MEDIUMTEXT NOT NULL,
  `Número` MEDIUMTEXT NOT NULL,
  `Piso` MEDIUMTEXT NOT NULL,
  `Puerta` MEDIUMTEXT NOT NULL,
  `Ciudad` MEDIUMTEXT NOT NULL,
  `CP` MEDIUMTEXT NOT NULL,
  `País` MEDIUMTEXT NOT NULL,
  `Telf` DECIMAL(10,0) NOT NULL,
  `FAX` DECIMAL(10,0) NOT NULL,
  `NIF` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Lentes` VARCHAR(45) NOT NULL,
  `Montura` MULTILINESTRING NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `ColorLente` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  `idProveedor` VARCHAR(45) NOT NULL,
  `Stock` VARCHAR(45) NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `Telf` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Fecha_Reg` DATE NOT NULL,
  `Recomendado` LONGTEXT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT NOT NULL,
  `Nombre` MEDIUMTEXT NOT NULL,
  `Apellido` MEDIUMTEXT NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Telf` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idEmpleado` VARCHAR(45) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  INDEX `fk_Ventas_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC),
  INDEX `fk_Ventas_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Ventas_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
