-- MySQL Script generated by MySQL Workbench
-- mié 23 oct 2019 13:41:21 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `NameUser` MEDIUMTEXT NOT NULL,
  `Password` MEDIUMTEXT NOT NULL,
  `Mail` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Videos` (
  `Idvideos` INT NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `Title` MEDIUMTEXT NOT NULL,
  `URL` VARCHAR(45) NOT NULL,
  `IdUser` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  INDEX `fk_Videos_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Videos_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
